
version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - ${NODE_HOST_PORT}:${NODE_CONTAINER_PORT}
    environment:
      - NODE_ENV=production
      - DB_HOST=${EXTERNAL_DB_HOST}
      - DB_USER=${EXTERNAL_DB_USER}
      - DB_PASSWORD=${EXTERNAL_DB_PASSWORD}
      - DB_NAME=${EXTERNAL_DB_NAME}
      - DB_PORT=${EXTERNAL_DB_PORT}
      - PORT=${NODE_CONTAINER_PORT}
    stdin_open: true
    tty: true