name: connect external db

on:
  push:
    branches:
      - "**"

jobs:
  deploy:
    name: connect external db
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Try to connect external db
        env:
          EXTERNAL_DB_HOST: ${{ secrets.EXTERNAL_DB_HOST }}
          EXTERNAL_DB_USER: ${{ secrets.EXTERNAL_DB_USER }}
          EXTERNAL_DB_NAME: ${{ secrets.EXTERNAL_DB_NAME }}
          EXTERNAL_DB_PORT: ${{ secrets.EXTERNAL_DB_PORT }}
          NODE_HOST_PORT: ${{ secrets.NODE_HOST_PORT }}
          NODE_CONTAINER_PORT: ${{ secrets.NODE_CONTAINER_PORT }}
        run: docker-compose -f docker/docker-compose.yml up -d